### ISSUE TITLE
The filter suddenly stopped working

### ISSUE THREAD

**Issue by villelahdenvuo** [actions/bin#19]
I configured a filter to only run my actions on issues with the label greenkeeper, but for some reason without me changing anything the filter started erroring. I think the event payload json has changed somehow.

Here's the config:

```workflow
action "filter-greenkeeper" {
  uses = "actions/bin/filter@b2bea0749eed6beb495a8fa194c071847af60ea1"
  args = "label greenkeeper"
}
```

And the logs:
```
...
Digest: sha256:2b563779b8eb5c34114dce5f547ef0e8506a5701123819159a3ae1b319f4f80e
Status: Downloaded newer image for gcr.io/github-actions-images/action-runner:latest
jq: error (at /github/workflow/event.json:1): Cannot iterate over null (null)

### FAILED filter-greenkeeper 10:43:31Z (36.507s)
```

Or maybe it crashes if the labels list is undefined?

**Comment by HaitamDow** [comment]
I'm getting the same issue with the filter action 
`Digest: sha256:2b563779b8eb5c34114dce5f547ef0e8506a5701123819159a3ae1b319f4f80e
Status: Downloaded newer image for gcr.io/github-actions-images/action-runner:latest
jq: error (at /github/workflow/event.json:1): Cannot iterate over null (null)

### FAILED pull request 20:37:44Z (15.866s)`

**Comment by nitan84** [comment]
Getting the same error as well for the filter action:

```
Digest: sha256:f747d8611fb26448f06a4245e252204859df6c7f81f04c248497c3e68c7740dd
Status: Downloaded newer image for gcr.io/github-actions-images/action-runner:latest
jq: error (at /github/workflow/event.json:1): Cannot iterate over null (null)
```

Any possible workarounds?

**Comment by nitan84** [comment]
With the help of a friend, found out that label filters do not work with push events:

[GitHub's Push event](https://developer.github.com/v3/activity/events/types/#pushevent) doesn't have `.issue.labels[].name` in its payload, which is needed by the filters (https://github.com/actions/bin/blob/master/filter/bin/label#L5)

**Comment by villelahdenvuo** [comment]
@nitan84 I only used issues and pull_request events but still got this error.

**Comment by hfaulds** [comment]
I had a look at this and could replicate this error if `.issue.labels` in the payload wasn't an array (which definitely happens if the label filter is used with certain events (the same conclusion @nitan84 came to in https://github.com/actions/bin/issues/19#issuecomment-453924614).

I opened https://github.com/actions/bin/pull/24 to address this failure case.

@villelahdenvuo is it possible for you to capture the payload in a failure you're seeing (or give me access to the repo)?
