### ISSUE TITLE
Branch filter for releases

### ISSUE THREAD

**Issue by judge2020** [actions/bin#32]
The "branch" filter currently looks for the ref being `refs/heads/<branch>`, which is great for events like `push`, however, this does not work with the `release` event. With a release, the ref is `refs/tags/<tagname>`, making the current branch filter always fail.

The github webhook event file (`GITHUB_EVENT_PATH`) has the property `release.target_commitish`([1](https://developer.github.com/v3/activity/events/types/#releaseevent)), which *is* the branch name and will work for the release event.

One solution I see is the branch filter checking the action type to be `release` and then appropriately filtering based on the webhook event file. Or, if that is adding too much extra functionality to the filter, it could be handled via a new filter called something like `release_branch`.

**Comment by chrispat** [comment]
# Important

This action is deprecated in favor of using the [`run`](https://help.github.com/en/articles/workflow-syntax-for-github-actions#jobsjob_idstepsrun) script step in the new YAML language to run the various cli tools represented by these actions. 

For feature requests and feedback please head over to the community forum. https://github.community/t5/GitHub-Actions/bd-p/actions
