### ISSUE TITLE
Multiple environments in one workflow

### ISSUE THREAD

**Issue by DiederikvandenB** [actions/bin#33]
Hi, I started fiddling a bit with Github Actions, and so far it seems promising.

I do however have a couple of questions about using multiple environments within the same workflow. Firstly, it currently does not seem possible to do a `needs = ["action_1", "action_2"]` and allowing one of the actions to fail or respond with the neutral exit code. In reference to the screenshot (see the link below), we want to run the `Build Container` action despite one of the parent actions resulting in "Neutral".

Secondly, it would be awesome if it were possible to set environment variables which propagate to actions later in the workflow. As you can see in the attached screenshot, it would be nice if the `Production|Staging` actions can set an `APP_ENV` which can be used by the push/deploy actions.

Of course, it would be possible to create multiple workflows for this, but as the workflow increases in size and multiple environments are added, it becomes cumbersome to update the workflow for every variant.

[See screenshot](https://user-images.githubusercontent.com/6132723/52046857-0d265600-2548-11e9-8aee-952055450601.png)

Cheers!

**Comment by chrispat** [comment]
# Important

This action is deprecated in favor of using the [`run`](https://help.github.com/en/articles/workflow-syntax-for-github-actions#jobsjob_idstepsrun) script step in the new YAML language to run the various cli tools represented by these actions. 

For feature requests and feedback please head over to the community forum. https://github.community/t5/GitHub-Actions/bd-p/actions
