### ISSUE TITLE
Filter by branch - only 1 of 2 filters checked

### ISSUE THREAD

**Issue by chearmstrong** [actions/bin#34]
Hi.

I'm just setting up my first workflow - Im adding 2 filters. 1 to check for `develop` branch and another to check for `master`. This is due to wanting to deploy differently, depending on the branch.

However, the 2nd filter never runs. I'm not sure where I'm going wrong here.

![image](https://user-images.githubusercontent.com/10651067/52142068-89f02780-264f-11e9-83b5-562a8cea85b6.png)

Is there a way to do what I want?

Thanks in advance.

**Comment by thepwagner** [comment]
@chearmstrong this is only possible at the moment by splitting the branches into different workflows.
Once _any_ action in the workflow returns an error (including a filter not passing), all the actions that haven't executed yet will be cancelled.
The downside of splitting is that both workflows would run `Install`/`Test` on their way to the filter - duplicating effort.

Another option would be merging the `Deploy prod` and `Deploy dev` actions into a single action, then having it internally filter:
```
#!/bin/bash

if [[ $GITHUB_REF =~ "refs/heads/master" ]]; then
  echo "deploy master"
elif [[ $GITHUB_REF =~ "refs/heads/develop" ]]; then
  echo "deploy develop"
else
  # no match, neutral failure
  exit 78
fi
```

**Comment by chearmstrong** [comment]
@thepwagner I'll take a look at filtering internally - I think that would work best.

How/where do I add that script to the action?

**Comment by thepwagner** [comment]
@chearmstrong take a look at https://developer.github.com/actions/creating-github-actions/creating-a-new-action/ for instructions on creating a custom action  - your script would go in there.

**Comment by liamness** [comment]
I'm having the same issue as this - given the "flow diagram" like UI, it seems intuitive that you should be able to use them as an if / else rule. There's also nothing in the docs for either filters or actions that lets you know this is not how they work. The intuitive conclusion when you encounter this behaviour is that you must have done something wrong.

**Comment by jritsema** [comment]
Totally agree with @liamness.  Burned some time on this.  Would be nice to have a true conditional branching action that would allow more complex graphs.  The main use case being a git flow model where the develop branch gets deployed to a dev environment where the master branch gets deployed to a qa or prod environment.

**Comment by MasseGuillaume** [comment]
Similar issue:

![53682982-d769be00-3cfb-11e9-8826-8f947546b00c](https://user-images.githubusercontent.com/921490/58809177-7054f180-85e9-11e9-81fc-8e62c6809f87.png)

https://github.com/actions/bin/issues/13#issuecomment-468924656

a neutral exit on beta filter stops an unrelated branch deploy-master

**Comment by fnkr** [comment]
I had the same problem. I would have expected the "Docker Build" action to complete successfully, but it was cancelled because the "Release?" action exited neutrally. I want to build all commits (for testing) but only push tagged commits to the registry.

![](https://user-images.githubusercontent.com/616991/62791776-648c1c80-babd-11e9-978d-c442f7dc5d0f.png)

Because of this I had to do the check sequentially instead of parallel, which is slower.

![](https://user-images.githubusercontent.com/616991/62791816-77065600-babd-11e9-9266-db0cf576989e.png)

It was surprising for me that it is implemented that way. GitLab CI (which is what I've used before) does it differently.

**Comment by chrispat** [comment]
# Important

This action is deprecated in favor of using the [`run`](https://help.github.com/en/articles/workflow-syntax-for-github-actions#jobsjob_idstepsrun) script step in the new YAML language to run the various cli tools represented by these actions. 

For feature requests and feedback please head over to the community forum. https://github.community/t5/GitHub-Actions/bd-p/actions
