### ISSUE TITLE
Tag filtering doesn't work if pushed using --follow-tags

### ISSUE THREAD

**Issue by niksrc** [actions/bin#38]
Steps to reproduce this edge case:

Example workflow file (main.workflow)
```hcl
workflow "Build and Deploy" {
  on       = "push"
  resolves = ["Shell"]
}
action "Filters for GitHub Actions" {
  uses = "actions/bin/filter@master"
  args = "tag"
}
action "Shell" {
  uses = "actions/bin/sh@master"
  args = ["ls -ltr"]
}
```
```zsh
mkdir actions-test && cd actions-test
git init
echo "hello world" > temp.txt
git add . && git commit -m "init commit"
git push --follow-tags
```

**Comment by juanpicado** [comment]
I have the same issue. https://github.com/verdaccio/test_gh_actions/runs/63723737

```
Successfully built 48b07fbcbf1e
Successfully tagged gcr.io/gct-12-iis4u7nso8sj6xj5dpcoi6x/2e035e5fb8ad977ee790ec390dcc01678860173c8af763469ce9edd9953e17f2/0c0528c9cdfbbd04f6b09b464de94fce116e820f638af7674f4ac129bf3d799a:65252144853665b0f9b143e998543a3cd7227f9cd7211fc6eca814b22bd1473b
Already have image (with digest): gcr.io/github-actions-images/action-runner:latest
refs/heads/master does not match refs/tags/v*

### DECLINED Tag 21:43:04Z (10.787s)
```

**Comment by jonwinton** [comment]
If you use `npm version *` to update your package version before pushing and publishing then your `$GITHUB_REF` will be `refs/heads/master`.

For a quick solution you can run `npm version` with the `--no-git-tag-version` flag but you'll still need to create the tag and push it up to get the action to pass the filter.

**Comment by igorkamyshev** [comment]
Same issue. 🤓

**Comment by thepwagner** [comment]
👋 , this is a general issue that prevents triggering workflows from annotated tags.
We're working on a solution. The only workaround for now is to use lightweight tags.

**Comment by sschuberth** [comment]
@niksrc, in your first post I'm not getting how this triggers the issue: In your `action "Shell"`, aren't you missing a `needs = "Filters for GitHub Actions"`? And in the Git instructions, aren't you missing to add a local tag? Or is the point that the action gets triggered despite there being *no* tag?

**Comment by niksrc** [comment]
@sschuberth yes, I missed those steps while posting the issue. 
I think this got fixed recently. Actions are working for annotated tags for the last two weeks. Closing the issue now.
