### ISSUE TITLE
Filter commit message

### ISSUE THREAD

**Issue by nicolo-ribaudo** [actions/bin#39]
At Babel we are using a custom action to run a workflow only when a commit matches a specified pattern.
We are using it to create release tags on `v*.*.*` commits, and we will use it in the future to avoid running some workflows on commits marked as `[skip ci]`.
Do you think that it would be a good addition to the `filter` action of this repo?

You can see the implementation at https://github.com/babel/babel/tree/master/.github/actions/filter-commit-message and usage at https://github.com/babel/babel/blob/879a59085b4c6bf7fae744abe758774047427a58/.github/main.workflow#L18-L23

**Comment by ain** [comment]
Definitely a worthy suggestion, should be included in the filter!

**Comment by jumoog** [comment]
```YAML
      if: |
        contains(github.event.commits[0].message, '[skip ci]') == false &&
        contains(github.event.commits[0].message, '[ci skip]') == false
```

**Comment by thisismydesign** [comment]
Where can I find the `filter-commit-message` action now?

**Comment by chrispat** [comment]
# Important

This action is deprecated in favor of using the [`run`](https://help.github.com/en/articles/workflow-syntax-for-github-actions#jobsjob_idstepsrun) script step in the new YAML language to run the various cli tools represented by these actions. 

For feature requests and feedback please head over to the community forum. https://github.community/t5/GitHub-Actions/bd-p/actions
