### ISSUE TITLE
Paywall / subscription support

### ISSUE THREAD

**Issue by PatMyron** [actions/bin#41]
I've seen some people starting subscription business models for running Probot apps on repositories, and I think it'd be really cool if Github Actions supported subscriptions. I think it'd help a lot in making standalone Github Actions that aren't feeding into any existing ecosystem more sustainable

**Comment by chrispat** [comment]
# Important

This action is deprecated in favor of using the [`run`](https://help.github.com/en/articles/workflow-syntax-for-github-actions#jobsjob_idstepsrun) script step in the new YAML language to run the various cli tools represented by these actions. 

For feature requests and feedback please head over to the community forum. https://github.community/t5/GitHub-Actions/bd-p/actions
