### ISSUE TITLE
migrate to new bats-core

### ISSUE THREAD

**Issue by maxheld83** [actions/bin#46]
the currently used (original) version of bats seems to be abandoned, and there is a new pretty active fork at https://github.com/bats-core/bats-core

This is published as a separate `bats-core` pkg on apt and homebrew.

It also comes with its own Docker image (Alpine-based?) that might come in handy.

So to do this, I guess we'd have to:

- [ ] update the readme with correct link
- [ ] update the dockerfile (just use the bats-core "official" image)
- [ ] be done?

**Comment by chrispat** [comment]
# Important

This action is deprecated in favor of using the [`run`](https://help.github.com/en/articles/workflow-syntax-for-github-actions#jobsjob_idstepsrun) script step in the new YAML language to run the various cli tools represented by these actions. 

For feature requests and feedback please head over to the community forum. https://github.community/t5/GitHub-Actions/bd-p/actions
