### ISSUE TITLE
add more utilities to bats (e.g. curl)

### ISSUE THREAD

**Issue by maxheld83** [actions/bin#47]
I understand that github actions, and by extension, their docker images should be *very* slim and modular, so they can be easily reduced.

On the flipside, this can make it pretty hard to use some "utility" actions, such as `bats`, for which you might need other utility actions to get much use out of it.

For example, I need `curl` do get any use out of `bats` (because I need to compare stuff to online assets), but `curl` isn't inside `debian-slim` on which `bats` is based, so I'm out of luck.
The current idiomatic way to solve this would be, I guess, to run the `curl` github action in a prior step and write whatever I need to disc.

That'll do, but the `main.workflow` doesn't look very ... expressive if I add all these weird small steps.

So, I was wondering whether it would make sense to beef up the `bats` image a bit, because well, you typically need some of these utils to get much use out of it.

**Comment by chrispat** [comment]
# Important

This action is deprecated in favor of using the [`run`](https://help.github.com/en/articles/workflow-syntax-for-github-actions#jobsjob_idstepsrun) script step in the new YAML language to run the various cli tools represented by these actions. 

For feature requests and feedback please head over to the community forum. https://github.community/t5/GitHub-Actions/bd-p/actions
