### ISSUE TITLE
The deleted_branch and deleted_tags filters are not working as expected

### ISSUE THREAD

**Issue by FabricioMatteMassive** [actions/bin#50]
I did some debugging and the event payload (at `GITHUB_EVENT_PATH`) no longer has a `ref_type` field, not even when the event deletes a branch.

Therefore, the [`DELETE_EVENT_REF_TYPE` variable](https://github.com/actions/bin/blob/d820d56839906464fb7a57d1b4e1741cf5183efa/filter/bin/deleted_branch#L12) is always `null`.

**Comment by FabricioMatteMassive** [comment]
Initially reported by @diogoazevedos / @diogo-massive

**Comment by hfaulds** [comment]
I had a little look into this:

https://github.com/hfaulds/actions-tests/actions/workflow-runs/MDEwOkNoZWNrU3VpdGU5MDk1NTAzNA==

I see the `ref_type` field on `delete` events (when a branch is deleted). It looks to me like the filter action failed to build. I'll dig further into this and see what I find.

**Comment by FabricioMatteMassive** [comment]
Hello @hfaulds, thanks for looking into this.

Unfortunately I'm not able to open that link (404, probably permission).

However, 12 days ago I did a `cat $GITHUB_EVENT_PATH` inside an Action and got this:

    {"after":"0000000000000000000000000000000000000000","base_ref":null,"before":"4a704ceffb45a8b2cb523517663aa83b6ff8c947","commits":[],"compare":"https://github.com/getndazn/github-actions-playground/compare/4a704ceffb45...000000000000","created":false,"deleted":true,"forced":false,"head_commit":null,"organization":{"avatar_url":"https://avatars2.githubusercontent.com/u/21194695?v=4","description":"","events_url":"https://api.github.com/orgs/getndazn/events","hooks_url":"https://api.github.com/orgs/getndazn/hooks","id":21194695,"issues_url":"https://api.github.com/orgs/getndazn/issues","login":"getndazn","members_url":"https://api.github.com/orgs/getndazn/members{/member}","node_id":"MDEyOk9yZ2FuaXphdGlvbjIxMTk0Njk1","public_members_url":"https://api.github.com/orgs/getndazn/public_members{/member}","repos_url":"https://api.github.com/orgs/getndazn/repos","url":"https://api.github.com/orgs/getndazn"},"pusher":{"email":"38218139+FabricioMatteMassive@users.noreply.github.com","name":"FabricioMatteMassive"},"ref":"refs/heads/delete-branch-test","repository":{"archive_url":"https://api.github.com/repos/getndazn/github-actions-playground/{archive_format}{/ref}","archived":false,"assignees_url":"https://api.github.com/repos/getndazn/github-actions-playground/assignees{/user}","blobs_url":"https://api.github.com/repos/getndazn/github-actions-playground/git/blobs{/sha}","branches_url":"https://api.github.com/repos/getndazn/github-actions-playground/branches{/branch}","clone_url":"https://github.com/getndazn/github-actions-playground.git","collaborators_url":"https://api.github.com/repos/getndazn/github-actions-playground/collaborators{/collaborator}","comments_url":"https://api.github.com/repos/getndazn/github-actions-playground/comments{/number}","commits_url":"https://api.github.com/repos/getndazn/github-actions-playground/commits{/sha}","compare_url":"https://api.github.com/repos/getndazn/github-actions-playground/compare/{base}...{head}","contents_url":"https://api.github.com/repos/getndazn/github-actions-playground/contents/{+path}","contributors_url":"https://api.github.com/repos/getndazn/github-actions-playground/contributors","created_at":1552439170,"default_branch":"master","deployments_url":"https://api.github.com/repos/getndazn/github-actions-playground/deployments","description":null,"downloads_url":"https://api.github.com/repos/getndazn/github-actions-playground/downloads","events_url":"https://api.github.com/repos/getndazn/github-actions-playground/events","fork":false,"forks":0,"forks_count":0,"forks_url":"https://api.github.com/repos/getndazn/github-actions-playground/forks","full_name":"getndazn/github-actions-playground","git_commits_url":"https://api.github.com/repos/getndazn/github-actions-playground/git/commits{/sha}","git_refs_url":"https://api.github.com/repos/getndazn/github-actions-playground/git/refs{/sha}","git_tags_url":"https://api.github.com/repos/getndazn/github-actions-playground/git/tags{/sha}","git_url":"git://github.com/getndazn/github-actions-playground.git","has_downloads":true,"has_issues":false,"has_pages":false,"has_projects":false,"has_wiki":false,"homepage":null,"hooks_url":"https://api.github.com/repos/getndazn/github-actions-playground/hooks","html_url":"https://github.com/getndazn/github-actions-playground","id":175320895,"issue_comment_url":"https://api.github.com/repos/getndazn/github-actions-playground/issues/comments{/number}","issue_events_url":"https://api.github.com/repos/getndazn/github-actions-playground/issues/events{/number}","issues_url":"https://api.github.com/repos/getndazn/github-actions-playground/issues{/number}","keys_url":"https://api.github.com/repos/getndazn/github-actions-playground/keys{/key_id}","labels_url":"https://api.github.com/repos/getndazn/github-actions-playground/labels{/name}","language":"HCL","languages_url":"https://api.github.com/repos/getndazn/github-actions-playground/languages","license":null,"master_branch":"master","merges_url":"https://api.github.com/repos/getndazn/github-actions-playground/merges","milestones_url":"https://api.github.com/repos/getndazn/github-actions-playground/milestones{/number}","mirror_url":null,"name":"github-actions-playground","node_id":"MDEwOlJlcG9zaXRvcnkxNzUzMjA4OTU=","notifications_url":"https://api.github.com/repos/getndazn/github-actions-playground/notifications{?since,all,participating}","open_issues":2,"open_issues_count":2,"organization":"getndazn","owner":{"avatar_url":"https://avatars2.githubusercontent.com/u/21194695?v=4","email":"","events_url":"https://api.github.com/users/getndazn/events{/privacy}","followers_url":"https://api.github.com/users/getndazn/followers","following_url":"https://api.github.com/users/getndazn/following{/other_user}","gists_url":"https://api.github.com/users/getndazn/gists{/gist_id}","gravatar_id":"","html_url":"https://github.com/getndazn","id":21194695,"login":"getndazn","name":"getndazn","node_id":"MDEyOk9yZ2FuaXphdGlvbjIxMTk0Njk1","organizations_url":"https://api.github.com/users/getndazn/orgs","received_events_url":"https://api.github.com/users/getndazn/received_events","repos_url":"https://api.github.com/users/getndazn/repos","site_admin":false,"starred_url":"https://api.github.com/users/getndazn/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/getndazn/subscriptions","type":"Organization","url":"https://api.github.com/users/getndazn"},"private":true,"pulls_url":"https://api.github.com/repos/getndazn/github-actions-playground/pulls{/number}","pushed_at":1553197205,"releases_url":"https://api.github.com/repos/getndazn/github-actions-playground/releases{/id}","size":27,"ssh_url":"git@github.com:getndazn/github-actions-playground.git","stargazers":0,"stargazers_count":0,"stargazers_url":"https://api.github.com/repos/getndazn/github-actions-playground/stargazers","statuses_url":"https://api.github.com/repos/getndazn/github-actions-playground/statuses/{sha}","subscribers_url":"https://api.github.com/repos/getndazn/github-actions-playground/subscribers","subscription_url":"https://api.github.com/repos/getndazn/github-actions-playground/subscription","svn_url":"https://github.com/getndazn/github-actions-playground","tags_url":"https://api.github.com/repos/getndazn/github-actions-playground/tags","teams_url":"https://api.github.com/repos/getndazn/github-actions-playground/teams","trees_url":"https://api.github.com/repos/getndazn/github-actions-playground/git/trees{/sha}","updated_at":"2019-03-21T18:12:26Z","url":"https://github.com/getndazn/github-actions-playground","watchers":0,"watchers_count":0},"sender":{"avatar_url":"https://avatars1.githubusercontent.com/u/38218139?v=4","events_url":"https://api.github.com/users/FabricioMatteMassive/events{/privacy}","followers_url":"https://api.github.com/users/FabricioMatteMassive/followers","following_url":"https://api.github.com/users/FabricioMatteMassive/following{/other_user}","gists_url":"https://api.github.com/users/FabricioMatteMassive/gists{/gist_id}","gravatar_id":"","html_url":"https://github.com/FabricioMatteMassive","id":38218139,"login":"FabricioMatteMassive","node_id":"MDQ6VXNlcjM4MjE4MTM5","organizations_url":"https://api.github.com/users/FabricioMatteMassive/orgs","received_events_url":"https://api.github.com/users/FabricioMatteMassive/received_events","repos_url":"https://api.github.com/users/FabricioMatteMassive/repos","site_admin":false,"starred_url":"https://api.github.com/users/FabricioMatteMassive/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/FabricioMatteMassive/subscriptions","type":"User","url":"https://api.github.com/users/FabricioMatteMassive"}}

As you can see, there's `"deleted":true` but no `ref_type`.

I just did the test again by creating a branch and immediately deleting it, and I got:

    {"after":"0000000000000000000000000000000000000000","base_ref":null,"before":"4a704ceffb45a8b2cb523517663aa83b6ff8c947","commits":[],"compare":"https://github.com/getndazn/github-actions-playground/compare/4a704ceffb45...000000000000","created":false,"deleted":true,"forced":false,"head_commit":null,"organization":{"avatar_url":"https://avatars2.githubusercontent.com/u/21194695?v=4","description":"","events_url":"https://api.github.com/orgs/getndazn/events","hooks_url":"https://api.github.com/orgs/getndazn/hooks","id":21194695,"issues_url":"https://api.github.com/orgs/getndazn/issues","login":"getndazn","members_url":"https://api.github.com/orgs/getndazn/members{/member}","node_id":"MDEyOk9yZ2FuaXphdGlvbjIxMTk0Njk1","public_members_url":"https://api.github.com/orgs/getndazn/public_members{/member}","repos_url":"https://api.github.com/orgs/getndazn/repos","url":"https://api.github.com/orgs/getndazn"},"pusher":{"email":"38218139+FabricioMatteMassive@users.noreply.github.com","name":"FabricioMatteMassive"},"ref":"refs/heads/test-delete-2","repository":{"archive_url":"https://api.github.com/repos/getndazn/github-actions-playground/{archive_format}{/ref}","archived":false,"assignees_url":"https://api.github.com/repos/getndazn/github-actions-playground/assignees{/user}","blobs_url":"https://api.github.com/repos/getndazn/github-actions-playground/git/blobs{/sha}","branches_url":"https://api.github.com/repos/getndazn/github-actions-playground/branches{/branch}","clone_url":"https://github.com/getndazn/github-actions-playground.git","collaborators_url":"https://api.github.com/repos/getndazn/github-actions-playground/collaborators{/collaborator}","comments_url":"https://api.github.com/repos/getndazn/github-actions-playground/comments{/number}","commits_url":"https://api.github.com/repos/getndazn/github-actions-playground/commits{/sha}","compare_url":"https://api.github.com/repos/getndazn/github-actions-playground/compare/{base}...{head}","contents_url":"https://api.github.com/repos/getndazn/github-actions-playground/contents/{+path}","contributors_url":"https://api.github.com/repos/getndazn/github-actions-playground/contributors","created_at":1552439170,"default_branch":"master","deployments_url":"https://api.github.com/repos/getndazn/github-actions-playground/deployments","description":null,"downloads_url":"https://api.github.com/repos/getndazn/github-actions-playground/downloads","events_url":"https://api.github.com/repos/getndazn/github-actions-playground/events","fork":false,"forks":0,"forks_count":0,"forks_url":"https://api.github.com/repos/getndazn/github-actions-playground/forks","full_name":"getndazn/github-actions-playground","git_commits_url":"https://api.github.com/repos/getndazn/github-actions-playground/git/commits{/sha}","git_refs_url":"https://api.github.com/repos/getndazn/github-actions-playground/git/refs{/sha}","git_tags_url":"https://api.github.com/repos/getndazn/github-actions-playground/git/tags{/sha}","git_url":"git://github.com/getndazn/github-actions-playground.git","has_downloads":true,"has_issues":false,"has_pages":false,"has_projects":false,"has_wiki":false,"homepage":null,"hooks_url":"https://api.github.com/repos/getndazn/github-actions-playground/hooks","html_url":"https://github.com/getndazn/github-actions-playground","id":175320895,"issue_comment_url":"https://api.github.com/repos/getndazn/github-actions-playground/issues/comments{/number}","issue_events_url":"https://api.github.com/repos/getndazn/github-actions-playground/issues/events{/number}","issues_url":"https://api.github.com/repos/getndazn/github-actions-playground/issues{/number}","keys_url":"https://api.github.com/repos/getndazn/github-actions-playground/keys{/key_id}","labels_url":"https://api.github.com/repos/getndazn/github-actions-playground/labels{/name}","language":"HCL","languages_url":"https://api.github.com/repos/getndazn/github-actions-playground/languages","license":null,"master_branch":"master","merges_url":"https://api.github.com/repos/getndazn/github-actions-playground/merges","milestones_url":"https://api.github.com/repos/getndazn/github-actions-playground/milestones{/number}","mirror_url":null,"name":"github-actions-playground","node_id":"MDEwOlJlcG9zaXRvcnkxNzUzMjA4OTU=","notifications_url":"https://api.github.com/repos/getndazn/github-actions-playground/notifications{?since,all,participating}","open_issues":2,"open_issues_count":2,"organization":"getndazn","owner":{"avatar_url":"https://avatars2.githubusercontent.com/u/21194695?v=4","email":"","events_url":"https://api.github.com/users/getndazn/events{/privacy}","followers_url":"https://api.github.com/users/getndazn/followers","following_url":"https://api.github.com/users/getndazn/following{/other_user}","gists_url":"https://api.github.com/users/getndazn/gists{/gist_id}","gravatar_id":"","html_url":"https://github.com/getndazn","id":21194695,"login":"getndazn","name":"getndazn","node_id":"MDEyOk9yZ2FuaXphdGlvbjIxMTk0Njk1","organizations_url":"https://api.github.com/users/getndazn/orgs","received_events_url":"https://api.github.com/users/getndazn/received_events","repos_url":"https://api.github.com/users/getndazn/repos","site_admin":false,"starred_url":"https://api.github.com/users/getndazn/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/getndazn/subscriptions","type":"Organization","url":"https://api.github.com/users/getndazn"},"private":true,"pulls_url":"https://api.github.com/repos/getndazn/github-actions-playground/pulls{/number}","pushed_at":1554215047,"releases_url":"https://api.github.com/repos/getndazn/github-actions-playground/releases{/id}","size":27,"ssh_url":"git@github.com:getndazn/github-actions-playground.git","stargazers":0,"stargazers_count":0,"stargazers_url":"https://api.github.com/repos/getndazn/github-actions-playground/stargazers","statuses_url":"https://api.github.com/repos/getndazn/github-actions-playground/statuses/{sha}","subscribers_url":"https://api.github.com/repos/getndazn/github-actions-playground/subscribers","subscription_url":"https://api.github.com/repos/getndazn/github-actions-playground/subscription","svn_url":"https://github.com/getndazn/github-actions-playground","tags_url":"https://api.github.com/repos/getndazn/github-actions-playground/tags","teams_url":"https://api.github.com/repos/getndazn/github-actions-playground/teams","trees_url":"https://api.github.com/repos/getndazn/github-actions-playground/git/trees{/sha}","updated_at":"2019-03-21T18:12:26Z","url":"https://github.com/getndazn/github-actions-playground","watchers":0,"watchers_count":0},"sender":{"avatar_url":"https://avatars1.githubusercontent.com/u/38218139?v=4","events_url":"https://api.github.com/users/FabricioMatteMassive/events{/privacy}","followers_url":"https://api.github.com/users/FabricioMatteMassive/followers","following_url":"https://api.github.com/users/FabricioMatteMassive/following{/other_user}","gists_url":"https://api.github.com/users/FabricioMatteMassive/gists{/gist_id}","gravatar_id":"","html_url":"https://github.com/FabricioMatteMassive","id":38218139,"login":"FabricioMatteMassive","node_id":"MDQ6VXNlcjM4MjE4MTM5","organizations_url":"https://api.github.com/users/FabricioMatteMassive/orgs","received_events_url":"https://api.github.com/users/FabricioMatteMassive/received_events","repos_url":"https://api.github.com/users/FabricioMatteMassive/repos","site_admin":false,"starred_url":"https://api.github.com/users/FabricioMatteMassive/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/FabricioMatteMassive/subscriptions","type":"User","url":"https://api.github.com/users/FabricioMatteMassive"}}

Again, there's `"deleted": true` and no `ref_type`.

Any ideas?

**Comment by hfaulds** [comment]
@FabricioMatteMassive which event are you using in your workflow's `on` block?

I've got `on = "delete"`, I think you might have `on = "push"`.

If this is the case then I think we should update our README to indicate the type of event each filter is designed to be used with.

**Comment by FabricioMatteMassive** [comment]
> I've got `on = "delete"`, I think you might have `on = "push"`.

@hfaulds That's correct, I want to handle `push` events that are not delete events. I think #51 can help with that.

Or, if you can bring this to tech review with the rest of the GitHub Actions team, I believe excluding `"delete": true` events from triggering `on = "push"` workflows would be a more sensible default.

I, like many other developers, have a GitHub flow where developers work in the same repository by creating feature/fix branches and requesting code review when merging to the main development branch. We like to delete merged branches to keep things tidy. So we always need to exclude `delete` events from running our `on = "push"` CI, as that could have unwanted or unexpected behavior such as re-deploying a CD pipeline.

Excluding `delete` events from triggering push workflows would be a sensible default, IMHO. If the user wants to handle delete events, they could use the `delete` event specifically, or there could be a new option in the workflow definition for `push` events.

If this cannot be changed, #51 would be useful to exclude `delete` events from `push` workflows.

> If this is the case then I think we should update our README to indicate the type of event each filter is designed to be used with.

> It might also make sense to use `$GITHUB_EVENT_NAME` to help warn users when a filter is being used with an incompatible event.

Sounds like a good idea. :+1:

**Comment by chrispat** [comment]
# Important

This action is deprecated in favor of using the [`run`](https://help.github.com/en/articles/workflow-syntax-for-github-actions#jobsjob_idstepsrun) script step in the new YAML language to run the various cli tools represented by these actions. 

For feature requests and feedback please head over to the community forum. https://github.community/t5/GitHub-Actions/bd-p/actions
