### ISSUE TITLE
Filter is broken for deployment events

### ISSUE THREAD

**Issue by webknjaz** [actions/bin#54]
See https://github.com/sanitizers/octomachinery/runs/89378515

It prints out `$GITHUB_REF is not set` and exits with an error, not a neutral status.

**Comment by chrispat** [comment]
# Important

This action is deprecated in favor of using the [`run`](https://help.github.com/en/articles/workflow-syntax-for-github-actions#jobsjob_idstepsrun) script step in the new YAML language to run the various cli tools represented by these actions. 

For feature requests and feedback please head over to the community forum. https://github.community/t5/GitHub-Actions/bd-p/actions
