### ISSUE TITLE
filter multiple branches

### ISSUE THREAD

**Issue by jritsema** [actions/bin#55]
Is it not possible to filter on multiple branches, or am I missing something?

I want to do one part of a workflow for all branches, then abort if the pushed branch isn't `develop` or `master`.

I would expect to be able to do something like...
```hcl
action "Branch filter" {
  uses = "actions/bin/filter@master"
  args = "branch 'develop|master'"
}
```

**Comment by hlogeon** [comment]
Any updates here, guys? How can I achieve this?

**Comment by styfle** [comment]
My solution was to copy/paste the Workflow and then make sure to name everything uniquely so that there was one Workflow per branch.

The downside is that I'll need to remember to make changes to both Workflows in the future since to ensure they both have the same actions/steps.

**Comment by Djiit** [comment]
I'd love to see that feature too

**Comment by chrispat** [comment]
# Important

This action is deprecated in favor of using the [`run`](https://help.github.com/en/articles/workflow-syntax-for-github-actions#jobsjob_idstepsrun) script step in the new YAML language to run the various cli tools represented by these actions. 

For feature requests and feedback please head over to the community forum. https://github.community/t5/GitHub-Actions/bd-p/actions
