### ISSUE TITLE
Feature Request: Tagged commit + branch master

### ISSUE THREAD

**Issue by allanchau** [actions/bin#57]
Is it possible to filter for a merge into master and a tagged commit?

i.e. I'm trying to implement this
```
workflow "Publish to NPM" {
  on = "push"
  resolves = ["Publish"]
}

action "master-branch-filter" {
  args = "branch master"
  uses = "actions/bin/filter@master"
}

action "Tagged commit" {
  args = "tag v*"
  needs = "master-branch-filter"
  uses = "actions/bin/filter@master"
}

action "Publish" {
  args = "publish --access public"
  needs = ["Tagged commit"]
  secrets = ["NPM_AUTH_TOKEN"]
  uses = "actions/npm@59b64a598378f31e49cb76f27d6f3312b582f680"
}

```

**Comment by chrispat** [comment]
# Important

This action is deprecated in favor of using the [`run`](https://help.github.com/en/articles/workflow-syntax-for-github-actions#jobsjob_idstepsrun) script step in the new YAML language to run the various cli tools represented by these actions. 

For feature requests and feedback please head over to the community forum. https://github.community/t5/GitHub-Actions/bd-p/actions
