### ISSUE TITLE
filter action gets polluted by parallel run (?)

### ISSUE THREAD

**Issue by maxheld83** [actions/bin#59]
I can't make sense of [this log](https://github.com/r-lib/ghactions/runs/128717259).

The workflow run was triggered **by a commit to the master branch** (as per the ui), but still, this filter-on-master action:

```
action "Master Branch" {
  uses = "actions/bin/filter@c6471707d308175c57dfe91963406ef205837dbd"
  needs = ["Check Package", "Build Website"]
  args = "branch master"
}
```

exits neutrally with:

```
refs/heads/homegrowncache does not match refs/heads/master

### DECLINED Master Branch 17:01:53Z (515ms)
```

This doesn't make sense.
The commit *was* on `master`, not `homegrowncache`.

The only explanation I have is that I *did* at around the same time commit to `homegrowncache` and I'm now worried that something on github's side might be cross-polluting these two triggered workflow runs with a ref from the other branch.

Hope this is helpful/ I have this right.

Would be great to get some feedback on this, because if true, it could cause some thorny edge cases.

If false, I'd be stupid, but could sleep better.

**Comment by thedarkwriter** [comment]
I'm currently tackling a similar issue. I'll commit a PR to a branch that honors a filter (integration) and three runs will execute.

**Comment by chrispat** [comment]
# Important

This action is deprecated in favor of using the [`run`](https://help.github.com/en/articles/workflow-syntax-for-github-actions#jobsjob_idstepsrun) script step in the new YAML language to run the various cli tools represented by these actions. 

For feature requests and feedback please head over to the community forum. https://github.community/t5/GitHub-Actions/bd-p/actions
