### ISSUE TITLE
Set the result to success, or allow for option to report success if result is neutral

### ISSUE THREAD

**Issue by mkj28** [actions/bin#63]
For example trying to filter for merged branches
```
action "check if branch merged" {
  uses = "actions/bin/filter@master"
  args = "merged true"
}
```
Current "neutral" status leaves the github status checks list expanded - this is not ideal, as it suggests for the human to review the list. Ideally either "neutral" let's the list be collapsed, or add option to override neutral to be success.

<img width="685" alt="2019-07-26_0020" src="https://user-images.githubusercontent.com/2279299/61933685-51b10e00-af3b-11e9-88e8-39a5c3667b47.png">

**Comment by chrispat** [comment]
# Important

This action is deprecated in favor of using the [`run`](https://help.github.com/en/articles/workflow-syntax-for-github-actions#jobsjob_idstepsrun) script step in the new YAML language to run the various cli tools represented by these actions. 

For feature requests and feedback please head over to the community forum. https://github.community/t5/GitHub-Actions/bd-p/actions
