### ISSUE TITLE
Add filter for directories

### ISSUE THREAD

**Issue by daniel-white** [actions/bin#64]
It would be nice to filter certain directories in the case of a mono-repo.

**Comment by chrispat** [comment]
# Important

This action is deprecated in favor of using the [`run`](https://help.github.com/en/articles/workflow-syntax-for-github-actions#jobsjob_idstepsrun) script step in the new YAML language to run the various cli tools represented by these actions. 

For feature requests and feedback please head over to the community forum. https://github.community/t5/GitHub-Actions/bd-p/actions
