### ISSUE TITLE
Workflow not created for tag ref

### ISSUE THREAD

**Issue by enisdenjo** [actions/bin#65]
Hello,

first and foremost, GitHub Actions are awesome and very simple to use, big like! Now that we got the pleasantries away, let's jump straight in.

I have an action **filter** in my workflow which filters **tags**.

[This commit](https://github.com/domonda/domonda-js/commit/37a2d1e79ccf83993e291b0090cf0f0d6335ea5b) has **multiple tags** on it. However, it did not create workflows for the tag refs; it created just one for `refs/heads/master`. The effect of this issue was that my packages were not published through GitHub Actions. Simply because the single workflow filtered `refs/heads/master` out and there were no others following the tag refs.

Check out the attached screenshot:
![Screenshot 2019-08-01 at 09 06 24](https://user-images.githubusercontent.com/11807600/62272738-11bac100-b43c-11e9-931f-b1a00d22e2b0.png)

Don't know if this is a bug with the workflows or am I doing something wrong; nevertheless, I'd be very grateful if you could help me out!

**Comment by enisdenjo** [comment]
Happened again... Same behaviour. Check out [this commit](https://github.com/domonda/domonda-js/commit/d49edd8b2e973cf6b68df783e04c3f0016f224a0).

![Screenshot 2019-08-01 at 20 48 49](https://user-images.githubusercontent.com/11807600/62319416-347dc180-b49e-11e9-9aae-de89ee17e93e.png)

**Comment by chrispat** [comment]
# Important

This action is deprecated in favor of using the [`run`](https://help.github.com/en/articles/workflow-syntax-for-github-actions#jobsjob_idstepsrun) script step in the new YAML language to run the various cli tools represented by these actions. 

For feature requests and feedback please head over to the community forum. https://github.community/t5/GitHub-Actions/bd-p/actions
