### ISSUE TITLE
Support regex for filtering

### ISSUE THREAD

**Issue by F21** [actions/bin#67]
I'd like to filter branches and tags using a regular expression. My use-case is to perform certain actions only if the tag or branch matches a regular expression.

I think this would be a great addition to the filter action.

**Comment by peaceiris** [comment]
With GitHub Actions beta v2, we can filter branches using built-in options without the filter actions.

[Filtering for specific branches | Configuring a workflow - GitHub Help](https://help.github.com/en/articles/configuring-a-workflow#filtering-for-specific-branches)

**Comment by F21** [comment]
@peaceiris The downside of the built in filtering is that it only supports the [gitignore pattern format](https://git-scm.com/docs/gitignore#_pattern_format) and does not support regex.

**Comment by songololo** [comment]
The current filtering system is a major headache for filtering tags.

For example:
I want to run an action matching `v*` tags but not those including `dev`.
i.e.
An action must run for `v1.0.0` but must not run for `v1.0.0.dev0`.

There appears no way to do this with the current glob pattern system.

**Comment by songololo** [comment]
https://github.com/actions/bin/issues/66#issuecomment-522815864

**Comment by chrispat** [comment]
# Important

This action is deprecated in favor of using the [`run`](https://help.github.com/en/articles/workflow-syntax-for-github-actions#jobsjob_idstepsrun) script step in the new YAML language to run the various cli tools represented by these actions. 

For feature requests and feedback please head over to the community forum. https://github.community/t5/GitHub-Actions/bd-p/actions
