### ISSUE TITLE
Update README.mds for new YAML syntax

### ISSUE THREAD

**Issue by brianjmurrell** [actions/bin#70]
The README.md files in each of the actions here seems to document the old syntax, is that correct?

If so, it would be nice to get them all updated to show how to use using the new YAML syntax.

**Comment by chrispat** [comment]
# Important

This action is deprecated in favor of using the [`run`](https://help.github.com/en/articles/workflow-syntax-for-github-actions#jobsjob_idstepsrun) script step in the new YAML language to run the various cli tools represented by these actions.
