### ISSUE TITLE
Move actions/bin to Javascript module to make calls on macOS available

### ISSUE THREAD

**Issue by SirWindfield** [actions/bin#73]
Because`bin` is currently a container actions, it is not possible to run it on other OS except Linux. It would be nice if it would be ported to a Javascript action that invokes commands instead, making it available to macOS and Windows too.

**Edit:** My use case is calling `brew` to install dependencies for my builds. I couldn't figure any other way and just realised that `bin` does not work on macOS.

**Comment by chrispat** [comment]
This action is deprecated in favor of using the [`run`](https://help.github.com/en/articles/workflow-syntax-for-github-actions#jobsjob_idstepsrun) script step in the new YAML language to run cli tools.
