### ISSUE TITLE
support for filtering multiple actions not working?

### ISSUE THREAD

**Issue by dx-pbuckley** [actions/bin#8]
I tried to get it down to a minimally reproducible case - this is what I'm seeing when trying to filter for multiple actions, e.g. on a PR that could be opened or synchronize.

```
pbuckley@lappy486:~/$ docker run -it -e GITHUB_EVENT_PATH=/fixtures/pr_synchronize.json --mount type=bind,source=~/fixtures,target=/fixtures github/filter:master action "synchronize"
pbuckley@lappy486:~/$ echo $?
0
pbuckley@lappy486:~/$ docker run -it -e GITHUB_EVENT_PATH=/fixtures/pr_synchronize.json --mount type=bind,source=~/fixtures,target=/fixtures github/filter:master action "opened|synchronize"
sh: 1: synchronize: not found
pbuckley@lappy486:~/$ echo $?
127
```

**Comment by vmosyaykin** [comment]
Resolved the issue by using
```
action "Filter" {
  uses = "actions/bin/filter@master"
  args = "action 'opened|synchronize'"
}
```

**Comment by dx-pbuckley** [comment]
agreed that resolves it @vmosyaykin ty!but I think there is a fix

**Comment by CodeDux** [comment]
Single quotes is the way to go. 

Otherwise I think the `|` sign gets processed by bash and it tries to run `synchronize` as a command, resulting in `sh: 1: synchronize: not found` since all arguments are passed to https://github.com/actions/bin/blob/b2bea0749eed6beb495a8fa194c071847af60ea1/filter/entrypoint.sh#L5

**Comment by dx-pbuckley** [comment]
I agree @CodeDux - my issue is that when this was in private beta, it worked differently/better (i.e. it didn't require the single quotes). I don't know and can't see what changed since the repo is new/different when it moved from private beta to semi-private-beta.

**Comment by hfaulds** [comment]
@dx-pbuckley I started looking into this and it changed in https://github.com/actions/bin/pull/2

I don't have any suggested fixes yet which both remove the need to double-quote and don't bring bag the bug that PR fixed but I will look into it

**Comment by angelarivera** [comment]
Hello @CodeDux, @dx-pbuckley, and @vmosyaykin 👋 Thanks for taking time to think this issue through and find workarounds that work best for you. The Actions team is currently working to resolve this problem and hope to simplify this issue for you soon!

**Comment by chrispat** [comment]
# Important

This action is deprecated in favor of using the [`run`](https://help.github.com/en/articles/workflow-syntax-for-github-actions#jobsjob_idstepsrun) script step in the new YAML language to run the various cli tools represented by these actions. 

For feature requests and feedback please head over to the community forum. https://github.community/t5/GitHub-Actions/bd-p/actions
